<?php

use Illuminate\Database\Seeder;
use Carbon\Carbon;

class ChoicesTableSeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
      $params =
        [
          [ //都道府県
            'view_no'                                     => 1,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '北海道',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 2,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '青森県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 3,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '岩手県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 4,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '宮城県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 5,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '秋田県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 6,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '山形県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 7,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '福島県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 8,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '茨城県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 9,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '栃木県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 10,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '群馬県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 11,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '埼玉県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 12,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '千葉県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 13,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '東京都',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 14,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '神奈川県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 15,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '新潟県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 16,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '富山県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 17,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '石川県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 18,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '福井県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 19,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '山梨県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 20,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '長野県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 21,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '岐阜県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 22,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '静岡県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 23,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '愛知県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 24,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '三重県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 25,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '滋賀県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 26,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '京都府',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 27,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '大阪府',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 28,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '兵庫県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 29,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '奈良県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 30,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '和歌山県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 31,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '鳥取県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 32,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '島根県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 33,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '岡山県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 34,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '広島県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 35,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '山口県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 36,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '徳島県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 37,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '香川県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 38,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '愛媛県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 39,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '高知県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 40,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '福岡県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 41,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '佐賀県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 42,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '長崎県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 43,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '熊本県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 44,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '大分県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 45,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '宮崎県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 46,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '鹿児島県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                     => 47,
            'block_id'                                   => 4,
            'choice_type'                                => 'select',
            'label_text'                                 => '沖縄県',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [ //イベント申し込みフォームのプリセット
            'view_no'                                    => 1,
            'block_id'                                   => 25,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'イベント名（20XX年X月X日 土曜日　13:00開催）',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 2,
            'block_id'                                   => 25,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'イベント名（20XX年X月X日 土曜日　15:00開催）',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 3,
            'block_id'                                   => 25,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'イベント名（20XX年X月X日 土曜日　17:00開催）',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 1,
            'block_id'                                   => 27,
            'choice_type'                                => 'radio',
            'label_text'                                 => '紹介',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 2,
            'block_id'                                   => 27,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'Facebook',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 3,
            'block_id'                                   => 27,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'メルマガ',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 4,
            'block_id'                                   => 27,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'ブログ',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 5,
            'block_id'                                   => 27,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'チラシ',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 6,
            'block_id'                                   => 27,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'ホームページ',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 7,
            'block_id'                                   => 27,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'その他',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 8,
            'block_id'                                   => 29,
            'choice_type'                                => 'checkbox',
            'label_text'                                 => '個人情報の取扱いに同意する',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [//アンケートフォームをプリセット
            'view_no'                                    => 1,
            'block_id'                                   => 30,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'テレビ',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 2,
            'block_id'                                   => 30,
            'choice_type'                                => 'radio',
            'label_text'                                 => '新聞',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 3,
            'block_id'                                   => 30,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'ラジオ',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 4,
            'block_id'                                   => 30,
            'choice_type'                                => 'radio',
            'label_text'                                 => '雑誌',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 5,
            'block_id'                                   => 30,
            'choice_type'                                => 'radio',
            'label_text'                                 => '企業のホームページ',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 6,
            'block_id'                                   => 30,
            'choice_type'                                => 'radio',
            'label_text'                                 => '価格比較サイト・クチコミサイト',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 7,
            'block_id'                                   => 30,
            'choice_type'                                => 'radio',
            'label_text'                                 => '検索エンジン',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 8,
            'block_id'                                   => 30,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'インターネット広告',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 9,
            'block_id'                                   => 30,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'メールマガジン',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 10,
            'block_id'                                   => 30,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'SNS・ブログ',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 11,
            'block_id'                                   => 30,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'ダイレクトメール',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 12,
            'block_id'                                   => 30,
            'choice_type'                                => 'radio',
            'label_text'                                 => '店員の説明',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 13,
            'block_id'                                   => 30,
            'choice_type'                                => 'radio',
            'label_text'                                 => '店頭のポスター・POP',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 14,
            'block_id'                                   => 30,
            'choice_type'                                => 'radio',
            'label_text'                                 => '店頭で実物を見て',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 15,
            'block_id'                                   => 30,
            'choice_type'                                => 'radio',
            'label_text'                                 => '交通広告・看板',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 16,
            'block_id'                                   => 30,
            'choice_type'                                => 'radio',
            'label_text'                                 => '家族・友人・知人',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 17,
            'block_id'                                   => 30,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'その他',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 1,
            'block_id'                                   => 31,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'スーパーマーケット',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 2,
            'block_id'                                   => 31,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'コンビニ',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 3,
            'block_id'                                   => 31,
            'choice_type'                                => 'radio',
            'label_text'                                 => '100円ショップ',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 4,
            'block_id'                                   => 31,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'ドラッグストア',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 5,
            'block_id'                                   => 31,
            'choice_type'                                => 'radio',
            'label_text'                                 => '大型ショッピングセンター',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 6,
            'block_id'                                   => 31,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'ディスカウントストア',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 7,
            'block_id'                                   => 31,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'ホームセンター',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 8,
            'block_id'                                   => 31,
            'choice_type'                                => 'radio',
            'label_text'                                 => '百貨店・デパート',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 9,
            'block_id'                                   => 31,
            'choice_type'                                => 'radio',
            'label_text'                                 => '家電量販店',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 10,
            'block_id'                                   => 31,
            'choice_type'                                => 'radio',
            'label_text'                                 => '酒屋',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 11,
            'block_id'                                   => 31,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'ネット通販・カタログ通販',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 12,
            'block_id'                                   => 31,
            'choice_type'                                => 'radio',
            'label_text'                                 => '自動販売機',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 13,
            'block_id'                                   => 31,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'その他',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 1,
            'block_id'                                   => 32,
            'choice_type'                                => 'checkbox',
            'label_text'                                 => '味が良い',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 2,
            'block_id'                                   => 32,
            'choice_type'                                => 'checkbox',
            'label_text'                                 => '原材料が良い',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 3,
            'block_id'                                   => 32,
            'choice_type'                                => 'checkbox',
            'label_text'                                 => 'カロリーが少ない',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 4,
            'block_id'                                   => 32,
            'choice_type'                                => 'checkbox',
            'label_text'                                 => '流行している',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 5,
            'block_id'                                   => 32,
            'choice_type'                                => 'checkbox',
            'label_text'                                 => 'メーカー・ブランドが好き',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 6,
            'block_id'                                   => 32,
            'choice_type'                                => 'checkbox',
            'label_text'                                 => 'パッケージデザインが好き',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 7,
            'block_id'                                   => 32,
            'choice_type'                                => 'checkbox',
            'label_text'                                 => '量がちょうどよい',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 8,
            'block_id'                                   => 32,
            'choice_type'                                => 'checkbox',
            'label_text'                                 => '価格が手頃',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 9,
            'block_id'                                   => 32,
            'choice_type'                                => 'checkbox',
            'label_text'                                 => '広告が魅力的',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 10,
            'block_id'                                   => 32,
            'choice_type'                                => 'checkbox',
            'label_text'                                 => '店頭で目立っていた',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 11,
            'block_id'                                   => 32,
            'choice_type'                                => 'checkbox',
            'label_text'                                 => '良く買っているシリーズ',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 12,
            'block_id'                                   => 32,
            'choice_type'                                => 'checkbox',
            'label_text'                                 => '周囲の評判が良い',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 13,
            'block_id'                                   => 32,
            'choice_type'                                => 'checkbox',
            'label_text'                                 => 'ネットの評判・クチコミが良い',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 14,
            'block_id'                                   => 32,
            'choice_type'                                => 'checkbox',
            'label_text'                                 => 'その他',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 1,
            'block_id'                                   => 33,
            'choice_type'                                => 'radio',
            'label_text'                                 => '満足',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 2,
            'block_id'                                   => 33,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'やや満足',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 3,
            'block_id'                                   => 33,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'どちらともいえない',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 4,
            'block_id'                                   => 33,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'やや不満',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 5,
            'block_id'                                   => 33,
            'choice_type'                                => 'radio',
            'label_text'                                 => '不満',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 1,
            'block_id'                                   => 35,
            'choice_type'                                => 'radio',
            'label_text'                                 => '満足',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 2,
            'block_id'                                   => 35,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'やや満足',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 3,
            'block_id'                                   => 35,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'どちらともいえない',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 4,
            'block_id'                                   => 35,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'やや不満',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 5,
            'block_id'                                   => 35,
            'choice_type'                                => 'radio',
            'label_text'                                 => '不満',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 1,
            'block_id'                                   => 36,
            'choice_type'                                => 'radio',
            'label_text'                                 => '満足',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 2,
            'block_id'                                   => 36,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'やや満足',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 3,
            'block_id'                                   => 36,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'どちらともいえない',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 4,
            'block_id'                                   => 36,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'やや不満',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 5,
            'block_id'                                   => 36,
            'choice_type'                                => 'radio',
            'label_text'                                 => '不満',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 1,
            'block_id'                                   => 37,
            'choice_type'                                => 'radio',
            'label_text'                                 => '満足',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 2,
            'block_id'                                   => 37,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'やや満足',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 3,
            'block_id'                                   => 37,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'どちらともいえない',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 4,
            'block_id'                                   => 37,
            'choice_type'                                => 'radio',
            'label_text'                                 => 'やや不満',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 5,
            'block_id'                                   => 37,
            'choice_type'                                => 'radio',
            'label_text'                                 => '不満',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 1,
            'block_id'                                   => 38,
            'choice_type'                                => 'radio',
            'label_text'                                 => '男性',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 2,
            'block_id'                                   => 38,
            'choice_type'                                => 'radio',
            'label_text'                                 => '女性',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 1,
            'block_id'                                   => 39,
            'choice_type'                                => 'select',
            'label_text'                                 => '10代以下（19歳以下）',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 2,
            'block_id'                                   => 39,
            'choice_type'                                => 'select',
            'label_text'                                 => '20代',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 3,
            'block_id'                                   => 39,
            'choice_type'                                => 'select',
            'label_text'                                 => '30代',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 4,
            'block_id'                                   => 39,
            'choice_type'                                => 'select',
            'label_text'                                 => '40代',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 5,
            'block_id'                                   => 39,
            'choice_type'                                => 'select',
            'label_text'                                 => '50代',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 6,
            'block_id'                                   => 39,
            'choice_type'                                => 'select',
            'label_text'                                 => '60代',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
          [
            'view_no'                                    => 7,
            'block_id'                                   => 39,
            'choice_type'                                => 'select',
            'label_text'                                 => '70代以上',
            'image'                                      => null,
            'delete_flag'                                => 0,
          ],
        ];

        $now = Carbon::now();
        foreach ($params as $param) {
          $param['created_at'] = $now;
          $param['updated_at'] = $now;
          DB::table('choices')->insert($param);
      }
    }


}
